# Documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# Edit should be made in the dependabot.template.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/**/*"
    exclude-paths:
      - "setup-kind/kind.yml"
    schedule:
      interval: "weekly"
    groups:
      # https://github.com/dflook/terraform-github-actions
      # multiple action always released together
      dflook:
        patterns:
          - "dflook/*"
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/.github/actions/pipenv"
      - "/.github/actions/jira-get-or-create-release"
      - "/.github/actions/jira-set-fix-version"
      - "/.github/tests/python-scripts/jira-get-or-create-release"
      - "/.github/tests/python-scripts/jira-set-fix-version"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "feat(deps)"
      prefix-development: "chore(deps)"
    groups:
      python-packages:
        patterns:
          - "*"
