name: 'Setup jx-release-version'
description: 'Set up a specific version of jx-release-version and add it to the PATH.'
inputs:
  version:
    description: 'Version of jx-release-version'
    required: false
    default: 2.2.3
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/setup-github-release-binary@4387dba6fc37d3c25037f56e41b9b3fce68f709d
      with:
        repo: jenkins-x-plugins/jx-release-version
        version: ${{ inputs.version }}
        url_template: 'v${VERSION}/${NAME}-${OS}-${ARCH}.tar.gz'
