name: "Setup Kubepug"
description: "Install the Kubernetes preupgrade checker"
inputs:
  version:
    description: The kubepug version to install
    default: "1.7.1"
    required: false
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/setup-github-release-binary@b95729464f5425f23ae3d87f0151cf3889741f4a
      with:
        repo: kubepug/kubepug
        version: ${{ inputs.version }}
        url_template: 'v${VERSION}/${NAME}_${OS}_${ARCH}.tar.gz'
        test_args: 'version'
