name: 'Setup terraform-docs'
description: 'Setup terraform-docs and add it to the PATH.'
inputs:
  version:
    description: 'Version of terraform-docs'
    required: false
    default: 0.24.0
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/setup-github-release-binary@ef6ea717cf37f82c63d6f0f7db343e5421536d8e
      with:
        repo: terraform-docs/terraform-docs
        version: ${{ inputs.version }}
        url_template: 'v${VERSION}/${NAME}-v${VERSION}-${OS}-${ARCH}.tar.gz'
