name: 'Setup terraform-docs'
description: 'Setup terraform-docs and add it to the PATH.'
inputs:
  version:
    description: 'Version of terraform-docs'
    required: false
    default: 0.24.0
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/setup-github-release-binary@a4d5e8a1b4db955628c23fe5981c88064d8c358d
      with:
        repo: terraform-docs/terraform-docs
        version: ${{ inputs.version }}
        url_template: 'v${VERSION}/${NAME}-v${VERSION}-${OS}-${ARCH}.tar.gz'
