name: 'Setup updatecli'
description: 'Install updatecli binary'
inputs:
  version:
    description: 'Version of binary'
    default: 0.120.1
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/setup-github-release-binary@5a665d430cb3638745b7d1f66e5e25afcd6f61a4
      with:
        repo: updatecli/updatecli
        version: ${{ inputs.version }}
        url_template: 'v${VERSION}/${NAME}_${OS}_${ARCH}.tar.gz'
        test_args: 'version'
        x86_64_arch: 'x86_64'
