name: 'Setup updatecli'
description: 'Install updatecli binary'
inputs:
  version:
    description: 'Version of binary'
    default: 0.120.1
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/setup-github-release-binary@ffdb53f6ead6ff8d9be239d34d6c9aad4df7a7ef
      with:
        repo: updatecli/updatecli
        version: ${{ inputs.version }}
        url_template: 'v${VERSION}/${NAME}_${OS}_${ARCH}.tar.gz'
        test_args: 'version'
        x86_64_arch: 'x86_64'
