name: 'Setup updatecli'
description: 'Install updatecli binary'
inputs:
  version:
    description: 'Version of binary'
    default: 0.119.0
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/setup-github-release-binary@e98709bf3f97a1a06c14d2d09c0a160f52262c3b
      with:
        repo: updatecli/updatecli
        version: ${{ inputs.version }}
        url_template: 'v${VERSION}/${NAME}_${OS}_${ARCH}.tar.gz'
        test_args: 'version'
        x86_64_arch: 'x86_64'
