name: 'Setup Flux CLI'
description: 'Set up a specific version of Flux CLI and add it to the PATH.'
inputs:
  version:
    description: 'Version of Flux CLI'
    required: false
    default: 2.9.2
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/setup-github-release-binary@40a7d84f7a11f7a78453fc32812a27f8c6ab97f3
      with:
        binary_name: flux
        repo: fluxcd/flux2
        version: ${{ inputs.version }}
