name: 'Setup Flux CLI'
description: 'Set up a specific version of Flux CLI and add it to the PATH.'
inputs:
  version:
    description: 'Version of Flux CLI'
    required: false
    default: 2.8.8
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/setup-github-release-binary@39d442d80be69af1ca1929d9c914c1e7ed135276
      with:
        binary_name: flux
        repo: fluxcd/flux2
        version: ${{ inputs.version }}
