name: Release and Deploy Maven project slimmed
description: Release and Deploy project using maven `deploy`, prepares repository for next development version

inputs:
  release-version:
    required: true
    description: The version of the release (tag).
  development-version:
    required: true
    description: The version that will be set in pom files after the release (next dev version)
  release-profile:
    required: false
    description: Maven profile used for release. Defaults to "release".
    default: release
  maven-additional-profiles:
    required: false
    description: Additional Maven profiles/options for release. Should start with -P (e.g. "-P additional").
    default: ''
  create-tag:
    required: false
    description: Boolean if should create tag.
    default: 'true'

runs:
  using: composite
  steps:
    - name: Generate app token
      id: app-token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        client-id: ${{ vars.GH_APP_ENGINEERING_CONTRIB_CLIENT_ID }}
        private-key: ${{ secrets.GH_APP_ENGINEERING_CONTRIB_PRIVATE_KEY }}
        permission-contents: write

    - name: "Set release version to ${{ inputs.release-version }}"
      run: mvn -B -ntp versions:set -DnewVersion="${{ inputs.release-version }}" -DgenerateBackupPoms=false
      shell: bash

    - name: "Deploy release version ${{ inputs.release-version }}"
      run: mvn -B -ntp clean deploy -DskipTests -P ${{ inputs.release-profile }} ${{ inputs.maven-additional-profiles }} -Dproject.revision.key=${{ github.sha }}
      shell: bash

    - name: "Commit release version ${{ inputs.release-version }}"
      uses: iarekylew00t/verified-bot-commit@5b4e8852dc472093935b8debcb81459bb79f7986 # v2.3.2
      with:
        token: ${{ steps.app-token.outputs.token }}
        ref: ${{ github.event.pull_request.head.ref || github.ref }}
        files: |
          pom.xml
          **/pom.xml
        message: "[alfresco build][skip ci] Release version ${{ inputs.release-version }}"
    - name: "Tag release version"
      if: inputs.create-tag == 'true'
      run: |
        git tag "${{ inputs.release-version }}"
        git push origin "${{ inputs.release-version }}"
      shell: bash

    - name: "Set next development version to ${{ inputs.development-version }}"
      run: mvn -B -ntp versions:set -DnewVersion="${{ inputs.development-version }}" -DgenerateBackupPoms=false
      shell: bash

    - name: "Commit next development version ${{ inputs.development-version }}"
      uses: iarekylew00t/verified-bot-commit@5b4e8852dc472093935b8debcb81459bb79f7986 # v2.3.2
      with:
        token: ${{ steps.app-token.outputs.token }}
        ref: ${{ github.event.pull_request.head.ref || github.ref }}
        files: |
          pom.xml
          **/pom.xml
        message: "[alfresco build][skip ci] Prepare next development version ${{ inputs.development-version }}"
