name: Maven Release (Slim)
description: Sets the release version, deploys artifacts with Maven, optionally tags the release, then sets the next development version.

inputs:
  token:
    required: true
    description: GitHub token required for authentication.
  release-version:
    required: true
    description: The version of the release (tag).
  development-version:
    required: true
    description: The version that will be set in pom files after the release (next dev version)
  release-profile:
    required: false
    description: Maven profile used for release. Defaults to "release".
    default: release
  maven-args:
    required: false
    description: Additional Maven arguments for release. Defaults to "-DskipTests".
    default: -DskipTests
  create-tag:
    required: false
    description: Boolean if should create tag.
    default: 'true'
  commit-message-prefix:
    required: false
    description: Prefix used by bot for commit message. Defaults to "[skip ci]".
    default: '[skip ci]'

runs:
  using: composite
  steps:
    - name: "Set release version to ${{ inputs.release-version }}"
      run: mvn -B -ntp versions:set -DnewVersion="${{ inputs.release-version }}" -DgenerateBackupPoms=false
      shell: bash

    - name: "Deploy release version ${{ inputs.release-version }}"
      run: mvn -B -ntp clean deploy -P ${{ inputs.release-profile }} -Dproject.revision.key=${{ github.sha }} ${{ inputs.maven-args }}
      shell: bash

    - name: "Commit release version ${{ inputs.release-version }}"
      uses: iarekylew00t/verified-bot-commit@33985d44b7719dcaf0b854a0f4b0caad9bdc5b86 # v2.3.3
      with:
        token: ${{ inputs.token }}
        ref: ${{ github.event.pull_request.head.ref || github.ref }}
        files: |
          pom.xml
          **/pom.xml
        message: "${{ inputs.commit-message-prefix }} Release version ${{ inputs.release-version }}"
    - name: "Tag release version"
      if: inputs.create-tag == 'true'
      run: |
        git tag "${{ inputs.release-version }}"
        git push origin "${{ inputs.release-version }}"
      shell: bash

    - name: "Set next development version to ${{ inputs.development-version }}"
      run: mvn -B -ntp versions:set -DnewVersion="${{ inputs.development-version }}" -DgenerateBackupPoms=false
      shell: bash

    - name: "Commit next development version ${{ inputs.development-version }}"
      uses: iarekylew00t/verified-bot-commit@33985d44b7719dcaf0b854a0f4b0caad9bdc5b86 # v2.3.3
      with:
        token: ${{ inputs.token }}
        ref: ${{ github.event.pull_request.head.ref || github.ref }}
        files: |
          pom.xml
          **/pom.xml
        message: "${{ inputs.commit-message-prefix }} Prepare next development version ${{ inputs.development-version }}"
