name: Free GHA runner disk space
description: Frees up disk space on GitHub Actions hosted runners by removing unneeded software.
inputs:
  remove-dotnet:
    description: Removes .NET runtime and libraries
    required: false
    default: 'true'
  remove-haskell:
    description: Removes GHC (Haskell) artifacts
    required: false
    default: 'true'
  remove-tools-cache:
    description: Removes tools and dependencies cached
    required: false
    default: 'true'
  remove-android:
    description: Removes Android SDKs and Tools
    required: false
    default: 'true'
  remove-codeql:
    description: Removes CodeQL Action Bundles
    required: false
    default: 'true'
  remove-swift:
    description: Removes Swift toolchain and libraries
    required: false
    default: 'true'
  remove-powershell:
    description: Removes PowerShell Core installation
    required: false
    default: 'true'
  remove-docker-images:
    description: Removes cached Docker images
    required: false
    default: 'false'
  remove-paths:
    description: Additional collection of files/folders to be removed, separated by spaces
    default: ''
    required: false
  diagnose-top-offenders-enabled:
    description: Runs diagnostic steps to list top disk space offenders before and after cleanup
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Runner system report before modification
      shell: bash
      run: |
        echo "Memory and swap:"
        free -m
        echo

        echo "Available storage:"
        df -h
        echo

    - name: Run optional diagnostic of top offenders before cleanup
      if: inputs.diagnose-top-offenders-enabled == 'true'
      run: |
        sudo du -h --max-depth=4 /usr /opt | sort -hr 2>/dev/null | head -n 20 || true
      shell: bash

    - name: Remove unwanted software
      env:
        DOTNET_ROOT: /usr/share/dotnet
        ANDROID_ROOT: /usr/local/lib/android
        HASKELL_ROOT: /usr/local/.ghcup
        CODEQL_ROOT: /opt/hostedtoolcache/CodeQL
        SWIFT_ROOT: /usr/share/swift
        POWERSHELL_ROOT: /usr/local/share/powershell
      run: |
        if [[ ${{ inputs.remove-dotnet }} == 'true' && -d $DOTNET_ROOT ]]; then
          echo "Removing .NET runtime and libraries..."
          start_time=$(date +%s)
          du -sh $DOTNET_ROOT
          sudo rm -rf $DOTNET_ROOT
          end_time=$(date +%s)
          echo "Removed in $((end_time - start_time)) seconds"
        else
          echo "$DOTNET_ROOT not found"
        fi

        if [[ ${{ inputs.remove-android }} == 'true' && -d $ANDROID_ROOT ]]; then
          echo "Removing Android SDKs and Tools..."
          start_time=$(date +%s)
          du -sh $ANDROID_ROOT
          sudo rm -rf $ANDROID_ROOT
          end_time=$(date +%s)
          echo "Removed in $((end_time - start_time)) seconds"
        else
          echo "$ANDROID_ROOT not found"
        fi

        if [[ ${{ inputs.remove-haskell }} == 'true' && -d $HASKELL_ROOT ]]; then
          echo "Removing GHC (Haskell) artifacts..."
          start_time=$(date +%s)
          du -sh $HASKELL_ROOT
          sudo rm -rf $HASKELL_ROOT
          end_time=$(date +%s)
          echo "Removed in $((end_time - start_time)) seconds"
        else
          echo "$HASKELL_ROOT not found"
        fi

        if [[ ${{ inputs.remove-codeql }} == 'true' && -d $CODEQL_ROOT ]]; then
          echo "Removing CodeQL Action Bundles..."
          start_time=$(date +%s)
          du -sh $CODEQL_ROOT
          sudo rm -rf $CODEQL_ROOT
          end_time=$(date +%s)
          echo "Removed in $((end_time - start_time)) seconds"
        else
          echo "$CODEQL_ROOT not found"
        fi

        if [[ ${{ inputs.remove-tools-cache }} == 'true' && -d $AGENT_TOOLSDIRECTORY ]]; then
          echo "Removing tools and dependencies cache..."
          start_time=$(date +%s)
          du -sh $AGENT_TOOLSDIRECTORY
          sudo rm -rf $AGENT_TOOLSDIRECTORY/*
          end_time=$(date +%s)
          echo "Removed in $((end_time - start_time)) seconds"
        else
          echo "$AGENT_TOOLSDIRECTORY not found"
        fi

        if [[ ${{ inputs.remove-swift }} == 'true' && -d $SWIFT_ROOT ]]; then
          echo "Removing Swift toolchain and libraries..."
          start_time=$(date +%s)
          du -sh $SWIFT_ROOT
          sudo rm -rf $SWIFT_ROOT
          end_time=$(date +%s)
          echo "Removed in $((end_time - start_time)) seconds"
        else
          echo "$SWIFT_ROOT not found"
        fi

        if [[ ${{ inputs.remove-powershell }} == 'true' && -d $POWERSHELL_ROOT ]]; then
          echo "Removing PowerShell Core installation..."
          start_time=$(date +%s)
          du -sh $POWERSHELL_ROOT
          sudo rm -rf $POWERSHELL_ROOT
          end_time=$(date +%s)
          echo "Removed in $((end_time - start_time)) seconds"
        else
          echo "$POWERSHELL_ROOT not found"
        fi

        if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
          echo "Removing cached Docker images..."
          start_time=$(date +%s)
          sudo docker image prune --all --force
          end_time=$(date +%s)
          echo "Removed in $((end_time - start_time)) seconds"
        fi

        to_remove="${{ inputs.remove-paths }}"
        if [[ -n "$to_remove" ]]; then
          echo "Removing additional files/folders..."
          start_time=$(date +%s)

          for item in $to_remove; do
            echo "Removing $item ..."
            du -sh "$item"
            sudo rm -rf "$item"
          done

          end_time=$(date +%s)
          echo "Removed in $((end_time - start_time)) seconds"
        fi

        echo "Done removing unwanted software."
      shell: bash

    - name: Run optional diagnostic of top offenders after cleanup
      if: inputs.diagnose-top-offenders-enabled == 'true'
      run: |
        sudo du -h --max-depth=4 /usr /opt | sort -hr 2>/dev/null | head -n 20 || true
      shell: bash

    - name: Runner system report after cleanup
      run: |
        echo "Memory and swap:"
        free -m
        echo

        echo "Available storage:"
        df -h
      shell: bash
